### ISSUE TITLE
update 3.x microservices to work with 4.2+

### ISSUE THREAD

**Issue by trel** [irods/contrib#9]
- [ ] DATA_EXPIRY modification in msiSysMetaModify (https://github.com/irods/irods/issues/2885)
- [ ] modify file size in msiSysMetaModify (https://github.com/irods/irods/issues/2886)
- [ ] create microservice to encrypt a file (https://github.com/irods/irods/issues/2887)
- [ ] port msiStoreVersionWithTS (https://github.com/irods/irods/issues/2889)
- [ ] port msiDataObjAutoMove (https://github.com/irods/irods/issues/2890)
- [ ] port msiGetDataObjACL (https://github.com/irods/irods/issues/2891)
- [ ] port msiCopyAVUMetadata (https://github.com/irods/irods/issues/2892)
- [ ] port msiLoadACLFromDataObj (https://github.com/irods/irods/issues/2893)
- [ ] port msiCreateUserAccountsFromDataObj (https://github.com/irods/irods/issues/2894)
- [ ] create microservice to modify META_DATA_ATTR_UNITS (https://github.com/irods/irods/issues/2895)
- [ ] create microservice to modify META_COLL_ATTR_UNITS (https://github.com/irods/irods/issues/2896)
- [ ] port msiGuessDataType (https://github.com/irods/irods/issues/2897)
